apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "8192"
    machine.openshift.io/vCPU: "2"
  labels:
    app.kubernetes.io/instance: machineset
    machine.openshift.io/cluster-api-cluster: ngirard-xwxnh
  name: ngirard-xwxnh-worker-us-east-2a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ngirard-xwxnh
      machine.openshift.io/cluster-api-machineset: ngirard-xwxnh-worker-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ngirard-xwxnh
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ngirard-xwxnh-worker-us-east-2a
    spec:
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-09145c219cb4df3e1
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ngirard-xwxnh-worker-profile
          instanceType: m5.large
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ngirard-xwxnh-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ngirard-xwxnh-private-us-east-2a
          tags:
          - name: kubernetes.io/cluster/ngirard-xwxnh
            value: owned
          userDataSecret:
            name: worker-user-data
